# cudnnDataType_t
const CUDNN_DATA_FLOAT = Cint(0)
const CUDNN_DATA_DOUBLE = Cint(1)
const CUDNN_DATA_HALF = Cint(2)
const CUDNN_DATA_INT8 = Cint(3)
const CUDNN_DATA_INT32 = Cint(4)
const CUDNN_DATA_INT8x4 = Cint(5)

# cudnnNanPropagation_t
const CUDNN_NOT_PROPAGATE_NAN = Cint(0)
const CUDNN_PROPAGATE_NAN = Cint(1)

# cudnnMathType_t
const CUDNN_DEFAULT_MATH = Cint(0)
const CUDNN_TENSOR_OP_MATH = Cint(1)

# cudnnDeterminism_t
const CUDNN_NON_DETERMINISTIC = Cint(0)
const CUDNN_DETERMINISTIC = Cint(1)

# cudnnTensorFormat_t
const CUDNN_TENSOR_NCHW = Cint(0)
const CUDNN_TENSOR_NHWC = Cint(1)
const CUDNN_TENSOR_NCHW_VECT_C = Cint(2)

# cudnnOpTensorOp_t
const CUDNN_OP_TENSOR_ADD = Cint(0)
const CUDNN_OP_TENSOR_MUL = Cint(1)
const CUDNN_OP_TENSOR_MIN = Cint(2)
const CUDNN_OP_TENSOR_MAX = Cint(3)
const CUDNN_OP_TENSOR_SQRT = Cint(4)
const CUDNN_OP_TENSOR_NOT = Cint(5)

# cudnnReduceTensorOp_t
const CUDNN_REDUCE_TENSOR_ADD = Cint(0)
const CUDNN_REDUCE_TENSOR_MUL = Cint(1)
const CUDNN_REDUCE_TENSOR_MIN = Cint(2)
const CUDNN_REDUCE_TENSOR_MAX = Cint(3)
const CUDNN_REDUCE_TENSOR_AMAX = Cint(4)
const CUDNN_REDUCE_TENSOR_AVG = Cint(5)
const CUDNN_REDUCE_TENSOR_NORM1 = Cint(6)
const CUDNN_REDUCE_TENSOR_NORM2 = Cint(7)
const CUDNN_REDUCE_TENSOR_MUL_NO_ZEROS = Cint(8)

# cudnnReduceTensorIndices_t
const CUDNN_REDUCE_TENSOR_NO_INDICES = Cint(0)
const CUDNN_REDUCE_TENSOR_FLATTENED_INDICES = Cint(1)

# cudnnIndicesType_t
const CUDNN_32BIT_INDICES = Cint(0)
const CUDNN_64BIT_INDICES = Cint(1)
const CUDNN_16BIT_INDICES = Cint(2)
const CUDNN_8BIT_INDICES = Cint(3)

# cudnnConvolutionMode_t
const CUDNN_CONVOLUTION = Cint(0)
const CUDNN_CROSS_CORRELATION = Cint(1)

# cudnnConvolutionFwdPreference_t
const CUDNN_CONVOLUTION_FWD_NO_WORKSPACE = Cint(0)
const CUDNN_CONVOLUTION_FWD_PREFER_FASTEST = Cint(1)
const CUDNN_CONVOLUTION_FWD_SPECIFY_WORKSPACE_LIMIT = Cint(2)

# cudnnConvolutionFwdAlgo_t
const CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM = Cint(0)
const CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM = Cint(1)
const CUDNN_CONVOLUTION_FWD_ALGO_GEMM = Cint(2)
const CUDNN_CONVOLUTION_FWD_ALGO_DIRECT = Cint(3)
const CUDNN_CONVOLUTION_FWD_ALGO_FFT = Cint(4)
const CUDNN_CONVOLUTION_FWD_ALGO_FFT_TILING = Cint(5)
const CUDNN_CONVOLUTION_FWD_ALGO_WINOGRAD = Cint(6)
const CUDNN_CONVOLUTION_FWD_ALGO_WINOGRAD_NONFUSED = Cint(7)
const CUDNN_CONVOLUTION_FWD_ALGO_COUNT = Cint(8)

# cudnnConvolutionBwdFilterPreference_t
const CUDNN_CONVOLUTION_BWD_FILTER_NO_WORKSPACE = Cint(0)
const CUDNN_CONVOLUTION_BWD_FILTER_PREFER_FASTEST = Cint(1)
const CUDNN_CONVOLUTION_BWD_FILTER_SPECIFY_WORKSPACE_LIMIT = Cint(2)

# cudnnConvolutionBwdFilterAlgo_t
const CUDNN_CONVOLUTION_BWD_FILTER_ALGO_0 = Cint(0)
const CUDNN_CONVOLUTION_BWD_FILTER_ALGO_1 = Cint(1)
const CUDNN_CONVOLUTION_BWD_FILTER_ALGO_FFT = Cint(2)
const CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3 = Cint(3)
const CUDNN_CONVOLUTION_BWD_FILTER_ALGO_WINOGRAD = Cint(4)
const CUDNN_CONVOLUTION_BWD_FILTER_ALGO_WINOGRAD_NONFUSED = Cint(5)
const CUDNN_CONVOLUTION_BWD_FILTER_ALGO_FFT_TILING = Cint(6)
const CUDNN_CONVOLUTION_BWD_FILTER_ALGO_COUNT = Cint(7)

# cudnnConvolutionBwdDataPreference_t
const CUDNN_CONVOLUTION_BWD_DATA_NO_WORKSPACE = Cint(0)
const CUDNN_CONVOLUTION_BWD_DATA_PREFER_FASTEST = Cint(1)
const CUDNN_CONVOLUTION_BWD_DATA_SPECIFY_WORKSPACE_LIMIT = Cint(2)

# cudnnConvolutionBwdDataAlgo_t
const CUDNN_CONVOLUTION_BWD_DATA_ALGO_0 = Cint(0)
const CUDNN_CONVOLUTION_BWD_DATA_ALGO_1 = Cint(1)
const CUDNN_CONVOLUTION_BWD_DATA_ALGO_FFT = Cint(2)
const CUDNN_CONVOLUTION_BWD_DATA_ALGO_FFT_TILING = Cint(3)
const CUDNN_CONVOLUTION_BWD_DATA_ALGO_WINOGRAD = Cint(4)
const CUDNN_CONVOLUTION_BWD_DATA_ALGO_WINOGRAD_NONFUSED = Cint(5)
const CUDNN_CONVOLUTION_BWD_DATA_ALGO_COUNT = Cint(6)

# cudnnSoftmaxAlgorithm_t
const CUDNN_SOFTMAX_FAST = Cint(0)
const CUDNN_SOFTMAX_ACCURATE = Cint(1)
const CUDNN_SOFTMAX_LOG = Cint(2)

# cudnnSoftmaxMode_t
const CUDNN_SOFTMAX_MODE_INSTANCE = Cint(0)
const CUDNN_SOFTMAX_MODE_CHANNEL = Cint(1)

# cudnnPoolingMode_t
const CUDNN_POOLING_MAX = Cint(0)
const CUDNN_POOLING_AVERAGE_COUNT_INCLUDE_PADDING = Cint(1)
const CUDNN_POOLING_AVERAGE_COUNT_EXCLUDE_PADDING = Cint(2)
const CUDNN_POOLING_MAX_DETERMINISTIC = Cint(3)

# cudnnActivationMode_t
const CUDNN_ACTIVATION_SIGMOID = Cint(0)
const CUDNN_ACTIVATION_RELU = Cint(1)
const CUDNN_ACTIVATION_TANH = Cint(2)
const CUDNN_ACTIVATION_CLIPPED_RELU = Cint(3)
const CUDNN_ACTIVATION_ELU = Cint(4)

# cudnnLRNMode_t
const CUDNN_LRN_CROSS_CHANNEL_DIM1 = Cint(0)

# cudnnDivNormMode_t
const CUDNN_DIVNORM_PRECOMPUTED_MEANS = Cint(0)

# cudnnBatchNormMode_t
const CUDNN_BATCHNORM_PER_ACTIVATION = Cint(0)
const CUDNN_BATCHNORM_SPATIAL = Cint(1)
const CUDNN_BATCHNORM_SPATIAL_PERSISTENT = Cint(2)

# cudnnSamplerType_t
const CUDNN_SAMPLER_BILINEAR = Cint(0)

# cudnnRNNMode_t
const CUDNN_RNN_RELU = Cint(0)
const CUDNN_RNN_TANH = Cint(1)
const CUDNN_LSTM = Cint(2)
const CUDNN_GRU = Cint(3)

# cudnnDirectionMode_t
const CUDNN_UNIDIRECTIONAL = Cint(0)
const CUDNN_BIDIRECTIONAL = Cint(1)

# cudnnRNNInputMode_t
const CUDNN_LINEAR_INPUT = Cint(0)
const CUDNN_SKIP_INPUT = Cint(1)

# cudnnRNNAlgo_t
const CUDNN_RNN_ALGO_STANDARD = Cint(0)
const CUDNN_RNN_ALGO_PERSIST_STATIC = Cint(1)
const CUDNN_RNN_ALGO_PERSIST_DYNAMIC = Cint(2)

# cudnnCTCLossAlgo_t
const CUDNN_CTC_LOSS_ALGO_DETERMINISTIC = Cint(0)
const CUDNN_CTC_LOSS_ALGO_NON_DETERMINISTIC = Cint(1)
